package com.fluxfund.api.domain.audit;

public enum AuditEntityType {
    FINANCIAL_TRANSACTION,
    TRANSACTION_ALLOCATION,
    ATTACHMENT,
    SUPPORT_AGREEMENT,
    ORGANIZATION_SETTINGS,
    OFX_IMPORT,
    FUND,
    BANK_STATEMENT_DOCUMENT,
    CREDIT_CARD_STATEMENT,
    CLOSING_DOSSIER,
    CLOSING_DOSSIER_EXTRA_DOCUMENT,
    ORGANIZATION,
    ORGANIZATION_USER,
    ORGANIZATION_USER_INVITATION,
}