package com.fluxfund.api.domain.audit;

public enum AuditAction {
    CREATE,
    UPDATE,
    CANCEL,
    CLASSIFY,

    ADD_ALLOCATION,
    UPDATE_ALLOCATION,
    REMOVE_ALLOCATION,

    UPLOAD_ATTACHMENT,
    DELETE_ATTACHMENT,

    ACTIVATE,
    DEACTIVATE,

    CHANGE_DEFAULT_FUND,

    IMPORT_OFX,

    UPLOAD_BANK_STATEMENT_DOCUMENT,
    DELETE_BANK_STATEMENT_DOCUMENT,

    GENERATE_CLOSING_DOSSIER,

    UPLOAD_CLOSING_DOSSIER_EXTRA_DOCUMENT,
    UPDATE_CLOSING_DOSSIER_EXTRA_DOCUMENT,
    DELETE_CLOSING_DOSSIER_EXTRA_DOCUMENT,

    UPLOAD_CREDIT_CARD_STATEMENT_PDF,
    DELETE_CREDIT_CARD_STATEMENT_PDF,

    UPLOAD_ORGANIZATION_LOGO,
    DELETE_ORGANIZATION_LOGO,

    CHANGE_ROLE,

    REGENERATE_INVITATION,

    ACCEPT_INVITATION,

    DELETE_RECEIPT_DRAFT,

    ISSUE_RECEIPT,

    CANCEL_RECEIPT,

    REISSUE_RECEIPT,
}