export type AuditAction =
  | "CREATE"
  | "UPDATE"
  | "CANCEL"
  | "CLASSIFY"
  | "ADD_ALLOCATION"
  | "UPDATE_ALLOCATION"
  | "REMOVE_ALLOCATION"
  | "UPLOAD_ATTACHMENT"
  | "DELETE_ATTACHMENT"
  | "ACTIVATE"
  | "DEACTIVATE"
  | "CHANGE_DEFAULT_FUND"
  | "IMPORT_OFX"
  | "UPLOAD_BANK_STATEMENT_DOCUMENT"
  | "DELETE_BANK_STATEMENT_DOCUMENT"
  | "GENERATE_CLOSING_DOSSIER"
  | "UPLOAD_CLOSING_DOSSIER_EXTRA_DOCUMENT"
  | "UPDATE_CLOSING_DOSSIER_EXTRA_DOCUMENT"
  | "DELETE_CLOSING_DOSSIER_EXTRA_DOCUMENT"
  | "UPLOAD_CREDIT_CARD_STATEMENT_PDF"
  | "DELETE_CREDIT_CARD_STATEMENT_PDF"
  | "UPLOAD_ORGANIZATION_LOGO"
  | "DELETE_ORGANIZATION_LOGO"
  | "CHANGE_ROLE"
  | "REGENERATE_INVITATION"
  | "ACCEPT_INVITATION"

export type AuditEntityType =
  | "FINANCIAL_TRANSACTION"
  | "TRANSACTION_ALLOCATION"
  | "ATTACHMENT"
  | "SUPPORT_AGREEMENT"
  | "ORGANIZATION_SETTINGS"
  | "OFX_IMPORT"
  | "FUND"
  | "BANK_STATEMENT_DOCUMENT"
  | "CREDIT_CARD_STATEMENT"
  | "CLOSING_DOSSIER"
  | "CLOSING_DOSSIER_EXTRA_DOCUMENT"
  | "ORGANIZATION"
  | "ORGANIZATION_USER"
  | "ORGANIZATION_USER_INVITATION"

export type AuditLog = {
  id: string
  organizationId: string
  actorUserId: string
  actorName: string | null
  actorEmail: string | null
  entityType: AuditEntityType
  entityId: string
  action: AuditAction
  description: string | null
  createdAt: string
}