spring.application.name=api

spring.datasource.url=jdbc:postgresql://localhost:5432/fluxfund_saas
spring.datasource.username=fluxfund
spring.datasource.password=12345678

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true

spring.web.cors.allowed-origin-patterns=http://localhost:5173


app.storage.local-root=./storage

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB